//! Tunnel — a macOS menu-bar app that supervises the b2c2 SSM tunnels.
//!
//! The menu-bar icon is color-coded so the current state is readable at a
//! glance (green = running, gray = stopped, amber = starting/reconnecting,
//! red = needs login / error). The actual tunnel work runs on a background
//! worker thread (see `worker.rs`) that never panics the process.

mod worker;

use std::process::Command;
use std::sync::mpsc;
use std::thread;

use tao::event::{Event, StartCause};
use tao::event_loop::{ControlFlow, EventLoopBuilder};
use tray_icon::menu::{CheckMenuItem, Menu, MenuEvent, MenuId, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

use worker::{Cmd, Event as WorkerEvent, Status};

// Embedded state icons (generated by assets/gen-icons.sh).
const ICON_RUNNING: &[u8] = include_bytes!("../assets/menubar/running.png"); // green: read
const ICON_RUNNING_WRITE: &[u8] = include_bytes!("../assets/menubar/running_write.png"); // blue: write
const ICON_STOPPED: &[u8] = include_bytes!("../assets/menubar/stopped.png");
const ICON_AMBER: &[u8] = include_bytes!("../assets/menubar/reconnecting.png");
const ICON_ALERT: &[u8] = include_bytes!("../assets/menubar/alert.png");

/// Events delivered into the tao event loop.
enum UserEvent {
    Menu(MenuId),
    Status(Status),
    WriteMode(bool),
}

fn load_icon(bytes: &[u8]) -> Icon {
    let image = image::load_from_memory(bytes)
        .expect("embedded icon must decode")
        .into_rgba8();
    let (w, h) = image.dimensions();
    Icon::from_rgba(image.into_raw(), w, h).expect("valid rgba icon")
}

/// Pick the icon from both the status and, when running, the read/write mode:
/// green = running read-only, blue = running write (primary).
fn icon_for(status: &Status, write_active: bool) -> Icon {
    let bytes = match status {
        Status::Running if write_active => ICON_RUNNING_WRITE,
        Status::Running => ICON_RUNNING,
        Status::Stopped => ICON_STOPPED,
        Status::Starting | Status::LoggingIn | Status::Reconnecting => ICON_AMBER,
        Status::NeedsLogin | Status::Error(_) => ICON_ALERT,
    };
    load_icon(bytes)
}

fn status_label(status: &Status) -> String {
    match status {
        Status::Stopped => "Stopped".into(),
        Status::Starting => "Starting…".into(),
        Status::LoggingIn => "Logging in to AWS…".into(),
        Status::Running => "Running".into(),
        Status::Reconnecting => "Reconnecting…".into(),
        Status::NeedsLogin => "Needs AWS login".into(),
        Status::Error(e) => format!("Error: {e}"),
    }
}

// --- login-item (Start at login) management via System Events --------------

/// Path to the enclosing `.app` bundle, if we're running from one.
fn app_bundle_path() -> Option<String> {
    let exe = std::env::current_exe().ok()?;
    // .../Tunnel.app/Contents/MacOS/tunnel  ->  .../Tunnel.app
    let bundle = exe.parent()?.parent()?.parent()?;
    if bundle.extension().map(|e| e == "app").unwrap_or(false) {
        Some(bundle.to_string_lossy().into_owned())
    } else {
        None
    }
}

fn osascript(script: &str) -> Option<String> {
    let out = Command::new("osascript")
        .args(["-e", script])
        .output()
        .ok()?;
    Some(String::from_utf8_lossy(&out.stdout).into_owned())
}

fn login_item_enabled() -> bool {
    osascript("tell application \"System Events\" to get the name of every login item")
        .map(|s| s.contains("Tunnel"))
        .unwrap_or(false)
}

fn set_login_item(enable: bool) {
    if enable {
        if let Some(path) = app_bundle_path() {
            let script = format!(
                "tell application \"System Events\" to make login item at end \
                 with properties {{path:\"{path}\", hidden:true}}"
            );
            let _ = osascript(&script);
        }
    } else {
        let _ = osascript("tell application \"System Events\" to delete login item \"Tunnel\"");
    }
}

/// Handles to the menu items we need to react to or update.
struct AppMenu {
    menu: Menu,
    status_item: MenuItem,
    start_id: MenuId,
    stop_id: MenuId,
    write_item: CheckMenuItem,
    write_id: MenuId,
    login_item: CheckMenuItem,
    login_id: MenuId,
    logs_id: MenuId,
    quit_id: MenuId,
}

fn build_menu() -> AppMenu {
    let menu = Menu::new();

    let status_item = MenuItem::new("● Stopped", false, None);
    let start_item = MenuItem::new("Start", true, None);
    let stop_item = MenuItem::new("Stop", true, None);
    let write_item = CheckMenuItem::new("Write mode (primary)", true, false, None);
    let login_item = CheckMenuItem::new("Start at login", true, login_item_enabled(), None);
    let logs_item = MenuItem::new("Open logs", true, None);
    let quit_item = MenuItem::new("Quit", true, None);

    menu.append_items(&[
        &status_item,
        &PredefinedMenuItem::separator(),
        &start_item,
        &stop_item,
        &PredefinedMenuItem::separator(),
        &write_item,
        &login_item,
        &PredefinedMenuItem::separator(),
        &logs_item,
        &quit_item,
    ])
    .expect("build menu");

    AppMenu {
        start_id: start_item.id().clone(),
        stop_id: stop_item.id().clone(),
        write_id: write_item.id().clone(),
        login_id: login_item.id().clone(),
        logs_id: logs_item.id().clone(),
        quit_id: quit_item.id().clone(),
        status_item,
        write_item,
        login_item,
        menu,
    }
}

/// A GUI-launched app inherits a minimal PATH, so the b2c2 / redis-cli / psql /
/// session-manager-plugin binaries won't be found. Build a PATH that works
/// regardless of where the user installed things:
///  1. the usual install locations, then
///  2. the user's real login-shell PATH (captures custom locations), then
///  3. whatever PATH we were launched with.
fn fix_path() {
    let home = std::env::var("HOME").unwrap_or_default();
    let mut parts = vec![
        format!("{home}/bin"),
        "/opt/homebrew/bin".into(),
        "/usr/local/bin".into(),
        "/usr/bin".into(),
        "/bin".into(),
        "/usr/sbin".into(),
    ];

    // Ask the user's login shell for its PATH so e.g. a b2c2 installed via
    // their shell profile is found even under an unusual layout.
    if let Ok(shell) = std::env::var("SHELL")
        && let Ok(out) = Command::new(&shell)
            .args(["-l", "-c", "printf %s \"$PATH\""])
            .output()
    {
        let shell_path = String::from_utf8_lossy(&out.stdout);
        let shell_path = shell_path.trim();
        if !shell_path.is_empty() {
            parts.push(shell_path.to_string());
        }
    }

    if let Ok(existing) = std::env::var("PATH") {
        parts.push(existing);
    }

    // SAFETY: called once at startup before any threads spawn child processes.
    unsafe { std::env::set_var("PATH", parts.join(":")) };
}

fn main() {
    fix_path();

    let event_loop = EventLoopBuilder::<UserEvent>::with_user_event().build();

    // Route tray menu clicks into the event loop.
    let menu_proxy = event_loop.create_proxy();
    MenuEvent::set_event_handler(Some(move |event: MenuEvent| {
        let _ = menu_proxy.send_event(UserEvent::Menu(event.id));
    }));

    // Spawn the supervised worker; it reports status back into the loop.
    let (cmd_tx, cmd_rx) = mpsc::channel::<Cmd>();
    let status_proxy = event_loop.create_proxy();
    thread::spawn(move || {
        worker::run(cmd_rx, move |event| {
            let user_event = match event {
                WorkerEvent::Status(status) => UserEvent::Status(status),
                WorkerEvent::WriteMode(on) => UserEvent::WriteMode(on),
            };
            let _ = status_proxy.send_event(user_event);
        });
    });

    // "Start at login" is controlled entirely by the menu toggle, which
    // reflects the current state on launch — no surprise auto-registration.

    // Created inside the event loop (required on macOS).
    let mut tray: Option<TrayIcon> = None;
    let mut menu: Option<AppMenu> = None;
    // Latest status + whether the running session is in write mode, so the icon
    // can reflect both dimensions (green = read, blue = write).
    let mut status = Status::Stopped;
    let mut write_active = false;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::NewEvents(StartCause::Init) => {
                let m = build_menu();
                let t = TrayIconBuilder::new()
                    .with_menu(Box::new(m.menu.clone()))
                    .with_tooltip("Tunnel — stopped")
                    .with_icon(load_icon(ICON_STOPPED))
                    .build()
                    .expect("build tray icon");
                tray = Some(t);
                menu = Some(m);
            }

            Event::UserEvent(UserEvent::Status(new_status)) => {
                status = new_status;
                if let (Some(tray), Some(menu)) = (tray.as_ref(), menu.as_ref()) {
                    let _ = tray.set_icon(Some(icon_for(&status, write_active)));
                    let label = status_label(&status);
                    let _ = tray.set_tooltip(Some(format!("Tunnel — {label}")));
                    menu.status_item.set_text(format!("● {label}"));
                }
            }

            Event::UserEvent(UserEvent::WriteMode(on)) => {
                // The worker reports the effective mode (on session start, and on
                // the 30-min auto-revert). Track it, refresh the icon, and keep
                // the checkbox in sync.
                write_active = on;
                if let (Some(tray), Some(menu)) = (tray.as_ref(), menu.as_ref()) {
                    let _ = tray.set_icon(Some(icon_for(&status, write_active)));
                    menu.write_item.set_checked(on);
                }
            }

            Event::UserEvent(UserEvent::Menu(id)) => {
                let Some(menu) = menu.as_ref() else { return };
                if id == menu.start_id {
                    let _ = cmd_tx.send(Cmd::Start);
                } else if id == menu.stop_id {
                    let _ = cmd_tx.send(Cmd::Stop);
                } else if id == menu.write_id {
                    let _ = cmd_tx.send(Cmd::SetWriteMode(menu.write_item.is_checked()));
                } else if id == menu.login_id {
                    set_login_item(menu.login_item.is_checked());
                } else if id == menu.logs_id {
                    let _ = Command::new("open").arg(worker::log_path()).status();
                } else if id == menu.quit_id {
                    let _ = cmd_tx.send(Cmd::Quit);
                    *control_flow = ControlFlow::Exit;
                }
            }

            _ => {}
        }
    });
}
